### PR TITLE
Install cuda via conda

### PR DESCRIPTION
**Pull request by thorstenwagner**
This PR modifies that the conda.yml so that it installs CUDA 11.7

### CODE REVIEW

**Comment by alisterburt** [comment]
looks like we might have two CUDA installs in the current recipe - nevertheless we're having all sorts of build issues and the CUDA build provided by nvidia through their channel may work better for us. @dtegunov is going to run some tests later and see if we want to pull this in

Thanks for taking the time to make a PR!

**Comment by dtegunov** [comment]
Thaks for the PR, Thorsten! As Alister pointed out, this creates some CUDA redundancy. The updated YML already had its own CUDA package, contrary to what the readme still said. I've been looking for a working combination that wouldn't involve conda-forge PyTorch, to no avail. However, this PR inspired me to give it one more try, and I think I finally found the right combination. Could you please try [this branch](https://github.com/warpem/warp/tree/torch-2)?

**Comment by thorstenwagner** [comment]
Thanks for the fast response!  I will try it next week. I also tried to work around conda forge cuda, but I didnt know that I can also use pytorch 2 :-)

**Comment by alisterburt** [comment]
@thorstenwagner there were small code changes required to make LibTorchSharp build against pytorch2 so you would have had extra trouble if you had tried 😝

**Comment by dtegunov** [comment]
Closing this as the updated warp_build.yml is in `main` now and hasn't resulted in issues for anyone as far as I can tell.

**Pull request closed without merging**
