### PR TITLE
add AreTomo2 compatibility

### LINKED ISSUE #46: task: update `ts_aretomo` WarpTool to AreTomo2
will close #41 when complete

### PR DESCRIPTION
**Pull request by alisterburt**
this PR adds changes for AreTomo2 compatibility and some useful debug output gated behind `WARP_DEBUG=1`

The AreTomo2 API is ~identical to AreTomo but when run on a stack called `TS_11.st` we end up with results called `TS_11_st.xf` in the `TS_11_Imod` folder

I also changed the way combinations of directories/filenames are generated so that you can easily specify a single tilt series directory in `ts_import_alignments` to only update a specific tilt series

closes #46

### CODE REVIEW

**Comment by alisterburt** [comment]
@jmdobbs @ThomasHoffman77 this should be working but I've only been able to test alignment and import separately as I'm unable to get AreTomo2 built and running in the same environment as Warp right now - could you test and see if this solves your issues with alignment import at #41 ?

**Comment by jmdobbs** [comment]
can confirm it's working :)

there is an (extremely) slight formatting error in the output in the command line, 0/1 is in the same line as Importing 2D transforms ....

> Running AreTomo with final average tilt axis angle:
0/1Importing 2D transforms from /struct/mahamid/jdobbs/warp2_testing/data_gseries/processing/tiltstack/gTS_003/gTS_003_Imod/gTS_003_st.xf
1/1, 00:00 remaining

**Comment by alisterburt** [comment]
Awesome - thanks for running the test! I'll have to wait until we can run it in our infrastructure before merging 🙂

**Comment by alisterburt** [comment]
confirmed working on our infra, thanks again @jmdobbs !

**Comment by alisterburt** [comment]
fyi @dtegunov compatible AreTomo2 is now available under the 'aretomo2' module in our module system

**Pull request merged**
